import type { CommercialBuildingEnergyAuditData } from "./types";

export const commercialBuildingEnergyAuditSampleData: CommercialBuildingEnergyAuditData = {
  reportInfo: {
    reportTitle: "Commercial Building Energy Audit Report",
    clientName: "Client Organisation Name",
    buildingType: "Commercial Office Building",
    location: "Building Location",
    auditPeriod: "Audit Period",
    reportDate: "Report Date",
    preparedBy: "SEE-Tech Solutions",
    documentVersion: "Version 1.0",
  },
  executiveSummary: {
    purposeText:
      "The purpose of this energy audit is to evaluate building energy performance, identify energy-saving projects, and present technically feasible measures with investment, savings, and implementation priority.",
    totalAnnualElectricityConsumption: "Data required",
    annualElectricityCost: "Data required",
    averageTariff: "Data required",
    numberOfProjects: 3,
    totalEnergySavingPotential: "Data required",
    totalAnnualCostSavingPotential: "Data required",
    totalEstimatedInvestment: "Data required",
    simplePaybackPeriod: "Data required",
    co2ReductionPotential: "Data required",
    keyObservations: [
      "HVAC operation and controls require detailed review for optimization.",
      "Lighting controls and fixture efficiency offer potential savings.",
      "Pump and motor operating hours should be validated against occupancy schedules.",
    ],
    conclusionAndWayForward:
      "SEE-Tech Solutions recommends validating the baseline measurements, confirming project costs, and prioritizing measures with lower payback and higher operational reliability.",
  },
  buildingProfile: {
    facilityName: "Facility Name",
    address: "Facility Address",
    typeOfBuilding: "Commercial Building",
    yearOfConstruction: "Data required",
    totalBuiltUpArea: "Data required m2",
    conditionedArea: "Data required m2",
    numberOfFloors: "Data required",
    occupancyType: "Office / Retail / Mixed Use",
    averageOccupancy: "Data required persons",
    operatingDaysAndHours: "Data required",
    facilityContactPerson: "Data required",
    auditDate: "Data required",
    seeTechAuditTeam: "SEE-Tech Audit Team",
  },
  buildingOperationDetails: [
    { areaFunction: "Office Areas", operatingHours: "Data required", remarks: "Typical weekday operation" },
    { areaFunction: "Common Areas", operatingHours: "Data required", remarks: "Data required" },
    { areaFunction: "Parking / Services", operatingHours: "Data required", remarks: "Data required" },
  ],
  utilityAndEnergySources: [
    { energySource: "Grid Electricity", use: "HVAC, lighting, pumps, plug loads", annualConsumption: "Data required kWh/year", annualCost: "Data required ₹/year" },
    { energySource: "Diesel Generator", use: "Backup power", annualConsumption: "Data required litres/year", annualCost: "Data required ₹/year" },
  ],
  electricalSupplyDetails: {
    supplyVoltage: "Data required kV",
    consumerNumber: "Data required",
    tariffCategory: "Data required",
    contractDemand: "Data required kVA",
    connectedLoad: "Data required kW",
    transformerCapacity: "Data required kVA",
    dgCapacity: "Data required kVA",
    apfcPanelCapacity: "Data required kVAR",
    averagePowerFactor: "Data required",
    billingType: "Data required",
    averageElectricityTariff: "Data required ₹/kWh",
  },
  electricityBillingSummary: [
    { month: "Month 1", kwh: "Data required", kvah: "Data required", maximumDemandKva: "Data required", pf: "Data required", billAmount: "Data required", specificConsumption: "Data required" },
    { month: "Month 2", kwh: "Data required", kvah: "Data required", maximumDemandKva: "Data required", pf: "Data required", billAmount: "Data required", specificConsumption: "Data required" },
    { month: "Month 3", kwh: "Data required", kvah: "Data required", maximumDemandKva: "Data required", pf: "Data required", billAmount: "Data required", specificConsumption: "Data required" },
  ],
  specificEnergyBenchmark: {
    buildingType: "Commercial Building",
    recommendedBenchmark: "Data required kWh/m2/year",
    annualElectricityConsumption: "Data required kWh/year",
    builtUpArea: "Data required m2",
    conditionedArea: "Data required m2",
    annualOccupancy: "Data required person-hours/year",
    specificEnergyConsumption: "Data required kWh/m2/year",
    referenceBenchmark: "Data required",
    improvementPotential: "Data required %",
  },
  majorEnergyConsumingSystems: [
    { system: "HVAC", majorEquipment: "Chillers / VRF / AHUs / FCUs", estimatedShare: "Data required %", remarks: "Cooling load and schedules to be validated" },
    { system: "Lighting", majorEquipment: "LED / fluorescent fixtures", estimatedShare: "Data required %", remarks: "Area-wise inventory required" },
    { system: "Pumps and Motors", majorEquipment: "CHW pumps, condenser pumps, domestic water pumps", estimatedShare: "Data required %", remarks: "Operating hours to be confirmed" },
  ],
  hvacSystemDetails: [
    { equipment: "Chiller / VRF Outdoor Unit", capacity: "Data required TR", quantity: "Data required", connectedLoad: "Data required kW", controlSystem: "Data required", remarks: "Data required" },
    { equipment: "AHU / FCU", capacity: "Data required CFM", quantity: "Data required", connectedLoad: "Data required kW", controlSystem: "Data required", remarks: "Data required" },
  ],
  lightingSystemDetails: [
    { area: "Office Area", existingFixture: "Data required", wattage: "Data required W", quantity: "Data required", operatingHours: "Data required h/day", controlType: "Data required" },
    { area: "Common Area", existingFixture: "Data required", wattage: "Data required W", quantity: "Data required", operatingHours: "Data required h/day", controlType: "Data required" },
  ],
  pumpsAndMotors: [
    { pumpOrMotor: "Chilled Water Pump", application: "HVAC circulation", ratingKw: "Data required kW", quantity: "Data required", operatingHours: "Data required h/day", controlMethod: "Data required", remarks: "Data required" },
    { pumpOrMotor: "Domestic Water Pump", application: "Water supply", ratingKw: "Data required kW", quantity: "Data required", operatingHours: "Data required h/day", controlMethod: "Data required", remarks: "Data required" },
  ],
  buildingAutomationControls: [
    { system: "HVAC Controls", existingControl: "Data required", observation: "Data required", savingOpportunity: "Schedule optimization / setpoint review" },
    { system: "Lighting Controls", existingControl: "Data required", observation: "Data required", savingOpportunity: "Occupancy sensors / daylight controls" },
  ],
  auditObservations: [
    { srNo: 1, observation: "HVAC operating schedule requires verification.", impact: "Potential excess kWh/year", recommendedProject: "HVAC controls optimization" },
    { srNo: 2, observation: "Lighting controls are not fully documented.", impact: "Potential avoidable operating hours", recommendedProject: "Lighting controls retrofit" },
  ],
  projects: [
    {
      projectNo: "Project 1",
      projectTitle: "HVAC Controls and Operating Schedule Optimization",
      system: "HVAC",
      location: "Building HVAC plant and occupied zones",
      equipmentCovered: "Chillers / VRF units, AHUs, FCUs, pumps",
      existingOperatingCondition: "Data required",
      proposedIntervention: "Optimize HVAC schedules, setpoints, and control logic.",
      expectedEnergySaving: "Data required kWh/year",
      expectedAnnualCostSaving: "Data required ₹/year",
      estimatedInvestment: "Data required ₹",
      simplePaybackPeriod: "Data required years",
      implementationDuration: "Data required weeks",
      implementationPriority: "High",
      existingSystemDescription: "Existing HVAC system operation and controls shall be documented during the detailed audit.",
      baselineData: [
        { parameter: "Connected HVAC Load", value: "Data required kW" },
        { parameter: "Operating Hours", value: "Data required h/year" },
        { parameter: "Measured Temperature", value: "Data required deg C" },
      ],
      measurementData: [
        { parameter: "Power Measurement", value: "Data required kW" },
        { parameter: "Airflow", value: "Data required CFM" },
      ],
      problemGapIdentified: "Controls, schedules, and setpoints may not be aligned with actual occupancy and load profile.",
      typicalGapTable: [
        { gap: "Extended operation", impact: "Excess kWh/year", evidenceRequired: "BMS trend / runtime logs" },
        { gap: "Low setpoint", impact: "Higher cooling energy", evidenceRequired: "Temperature trend" },
      ],
      proposedProjectDescription: "Implement optimized operating schedules, temperature setpoints, and control sequencing based on occupancy and load.",
      scopeOfWork: ["Review BMS schedules", "Validate zone comfort requirements", "Implement revised control logic", "Trend post-implementation operation"],
      keyActivities: ["Collect runtime data", "Prepare control change list", "Implement changes during approved window", "Verify comfort and savings"],
      rationaleForEnergySaving: "Reducing avoidable operating hours and improving setpoints reduces compressor, fan, and pump energy consumption.",
      savingRationaleTable: [
        { driver: "Runtime reduction", basis: "Avoided equipment operation" },
        { driver: "Setpoint optimization", basis: "Reduced cooling load" },
      ],
      energySavingCalculation: [
        { step: "Baseline annual kWh", value: "Data required" },
        { step: "Proposed annual kWh", value: "Data required" },
        { step: "Annual saving", value: "Data required kWh/year" },
      ],
      keyMetrics: [
        { metric: "Energy Saving", value: "Data required kWh/year" },
        { metric: "Cost Saving", value: "Data required ₹/year" },
        { metric: "Payback", value: "Data required years" },
      ],
      technicalSpecifications: [
        { item: "Control system", specification: "Existing BMS / controller details required" },
        { item: "Temperature setpoint", specification: "Data required deg C" },
      ],
      schematicFramework: "Control optimization framework shall be inserted after final technical review.",
      implementationDurationTable: [
        { activity: "Data review", duration: "Data required" },
        { activity: "Control implementation", duration: "Data required" },
      ],
      precautions: ["Maintain occupant comfort.", "Validate all control changes with facility team.", "Retain rollback settings."],
      measurementVerificationPlan: ["Record pre-implementation runtime and kWh.", "Record post-implementation runtime and kWh.", "Normalize for occupancy and weather where required."],
      benefitsOtherThanEnergySaving: ["Improved comfort control", "Reduced equipment wear", "Better operating visibility"],
      projectConclusion: "The project should be implemented after baseline validation and facility approval.",
      images: [{ filename: "", caption: "" }],
    },
    {
      projectNo: "Project 2",
      projectTitle: "Lighting Controls and Fixture Optimization",
      system: "Lighting",
      location: "Office, common, and service areas",
      equipmentCovered: "Lighting fixtures and controls",
      existingOperatingCondition: "Data required",
      proposedIntervention: "Upgrade controls and optimize fixture operation.",
      expectedEnergySaving: "Data required kWh/year",
      expectedAnnualCostSaving: "Data required ₹/year",
      estimatedInvestment: "Data required ₹",
      simplePaybackPeriod: "Data required years",
      implementationDuration: "Data required weeks",
      implementationPriority: "Medium",
      existingSystemDescription: "Existing lighting system inventory and operating schedule shall be confirmed area-wise.",
      baselineData: { installedLoad: "Data required kW", operatingHours: "Data required h/year" },
      measurementData: { luxLevel: "Data required lux", fixtureCount: "Data required" },
      problemGapIdentified: "Lighting may operate during unoccupied periods or at levels above functional requirement.",
      typicalGapTable: [{ gap: "Manual switching", impact: "Uncontrolled operating hours", evidenceRequired: "Site survey" }],
      proposedProjectDescription: "Install occupancy controls and revise switching groups where feasible.",
      scopeOfWork: ["Area-wise survey", "Control zoning", "Fixture and sensor installation", "Post-installation verification"],
      keyActivities: ["Prepare fixture inventory", "Measure lux levels", "Install approved controls", "Verify operation"],
      rationaleForEnergySaving: "Automatic controls reduce lighting operating hours without reducing required illumination.",
      savingRationaleTable: [{ driver: "Reduced operating hours", basis: "Occupancy-based switching" }],
      energySavingCalculation: [{ step: "Connected load x avoided hours", value: "Data required kWh/year" }],
      keyMetrics: [{ metric: "Lighting load reduction", value: "Data required kW" }],
      technicalSpecifications: [{ item: "Occupancy sensor", specification: "Data required" }],
      schematicFramework: "Lighting control schematic shall be inserted after final technical review.",
      implementationDurationTable: [{ activity: "Installation and commissioning", duration: "Data required" }],
      precautions: ["Maintain minimum lux levels.", "Avoid nuisance switching in occupied spaces."],
      measurementVerificationPlan: ["Record pre/post operating hours.", "Verify lux levels after implementation."],
      benefitsOtherThanEnergySaving: ["Improved controllability", "Longer fixture life"],
      projectConclusion: "Lighting optimization can be prioritized after fixture inventory and lux measurements are completed.",
      images: [],
    },
  ],
};
